var TEXT_HELP1              = "JUMP AND DIVE, ENTER THE WATER THE STRAIGHTEST YOU CAN";
var TEXT_HELP2              = "THE STRAIGHTEST THE ENTRANCE, THE HIGHEST THE SCORE!";
var TEXT_HELP_PREPARATION   = "HOLD CLICK TO PREPARE FOR JUMP";
var TEXT_HELP_JUMP          = "RELEASE TO JUMP";
var TEXT_HELP_FLIP          = "HOLD CLICK TO START FLIP";
var TEXT_HELP_RELEASE       = "RELEASE BEFORE ENTERING THE WATER";
var TEXT_TUTORIAL1          = "HOLD CLICK TO PREPARE FOR JUMP. RELEASE TO JUMP AT THE DESIRED ANGLE";
var TEXT_TUTORIAL2          = "HOLD CLICK TO START FLIPPING, RELEASE BEFORE ENTERING THE WATER!";

var TEXT_SCORE              = "SCORE";
var TEXT_LEVEL              = "LEVEL";
var TEXT_TURN               = "TURN";
var TEXT_ENCOURAGEMENT0     = "GREAT!";
var TEXT_ENCOURAGEMENT1     = "POOR!";
var TEXT_ENCOURAGEMENT2     = "PERFECT!";
var TEXT_LEVELWIN           = "LEVEL COMPLETED!";
var TEXT_GAMEOVER_DIVE      = "BAD LANDING!\nTRY AGAIN?";
var TEXT_GAMEOVER_RELEASE   = "CLICK NOT RELEASED!\nTRY AGAIN?";
var TEXT_GAMEOVER_ROTATION  = "NO FLIP!\nTRY AGAIN?";
var TEXT_GAMEOVER_HIT       = "YOU'VE BEEN HIT!\nTRY AGAIN?";
var TEXT_ARE_SURE           = "ARE YOU SURE YOU WANT TO EXIT? ALL UNSAVED PROGRESS WILL BE LOST";
var TEXT_TRY_AGAIN          = "TRY AGAIN!";
var TEXT_LEVELSELECT        = "SELECT LEVEL";
var TEXT_FLIP               = "FLIP!";

var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_CREDITS_DEVELOPED  = "DEVELOPED BY";
var TEXT_ERR_LS             = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

var TEXT_SHARE_IMAGE        = "200x200.jpg";
var TEXT_SHARE_TITLE        = "Congratulations!";
var TEXT_SHARE_MSG1         = "You collected <strong>";
var TEXT_SHARE_MSG2         = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1       = "My score is ";
var TEXT_SHARE_SHARE2       = " points! Can you do better";